# Generated by Django 5.2.8 on 2025-11-29 15:50

import django.db.models.deletion
import memory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=memory.models.get_publication_languages, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.author')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('authors', models.ManyToManyField(blank=True, through='memory.Authorship', to='memory.author')),
                ('publication_languages', models.ManyToManyField(related_name='publication_langauges', related_query_name='publication_languages', to='memory.publicationlanguage')),
            ],
        ),
        migrations.AddField(
            model_name='authorship',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.book'),
        ),
    ]
