# Generated by Django 5.2.8 on 2025-11-29 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0003_notecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='notecard',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='memory.book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notecard',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memory.note'),
        ),
    ]
