# Generated by Django 5.2.8 on 2025-11-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0005_category_container_categorisation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='container',
            name='book',
        ),
    ]
