# Generated by Django 5.2.8 on 2025-11-29 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0006_alter_category_options_remove_container_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memory.container'),
        ),
    ]
